### PR TITLE
🪟 Add aarch64 windows build

### PR DESCRIPTION
**Pull request by Jasper-Bekkers**
Compiled with ispc 1.20 because ispc 1.22 ran into an internal compiler error (reported here: https://github.com/ispc/ispc/issues/2713)

### CODE REVIEW

**Comment by MarijnS95** [comment]
Can we add this to the CI (instead)?

**Comment by MarijnS95** [comment]
Let's see: https://github.com/Traverse-Research/ispc-downsampler/actions/runs/7053442964

**Comment by MarijnS95** [comment]
>  thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ispc_compile-2.0.0\src\lib.rs:437:14:
>  Failed to find lib.exe for MSVC toolchain, aborting

@Jasper-Bekkers what do contributors and the CI need to install (on Windows) to be able to cross-compile the ISPC binary for this target when making changes to the ISPC files?

**Comment by MarijnS95** [comment]
Or was this all installed (Visual Studio Installer) and performed natively on the machine? I'm not sure how easy it would be to invoke that tool to add the aarch64 toolchain in the CI...

But I recall seeing such a setup in win32metadata which we could borrow.

**Comment by MarijnS95** [comment]
Were you building natively on the device? Then it makes obvious sense that you can build for the target.

Alas, expect this file to get out of date if you don't add the CI for it :(

**Comment by Jasper-Bekkers** [comment]
No I was cross compiling.

I'd love to see CI for it, but it looked like the CI step you tried didn't work, right?

**Comment by MarijnS95** [comment]
I've got a fix: https://github.com/Twinklebear/ispc-rs/pull/28

Haven't really checked why the 5-year-old `gcc` crate _was finding `lib.exe`_ for @Jasper-Bekkers but it doesn't really matter since our CI process does now too! https://github.com/Traverse-Research/ispc-downsampler/actions/runs/7089720459/job/19295068304

**Pull request merged**
